services:

    sge_web:
        build: .
        env_file:
            - .env
        restart: always
        ports:
            - 8000:8000
        depends_on:
            - sge_db

    sge_db:
        image: postgres:15
        ports:
            - 5432:5432
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=sge

volumes:
    postgres_data:
