# Generated by Django 5.0.1 on 2025-11-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_alter_supplier_address_alter_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='document_id',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
