# Generated by Django 5.0.1 on 2025-11-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='social_media',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
