# Generated by Django 5.0.1 on 2025-11-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costumers', '0002_costumer_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumer',
            name='social_media',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
